version: '3'
services:
#  api:
#    build: '.'
#    ports:
#      - '8080:8080'
#    depends_on:
#      - 'mongo'
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
volumes:
  mongodata:
